// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <WatchKit/WatchKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface GlanceController: WKInterfaceController

@property IBOutlet WKInterfaceLabel * periodNameLabel;
@property IBOutlet WKInterfaceImage * clockImage;
@property IBOutlet WKInterfaceLabel * timeRemainingLabel;

-(IBAction) initWithContext:(id) context;
-(IBAction) willActivate;
-(IBAction) didDeactivate;
-(IBAction) refresh;

@end

@interface InterfaceController: WKInterfaceController

@property IBOutlet WKInterfaceLabel * periodNameLabel;
@property IBOutlet WKInterfaceImage * clockImage;
@property IBOutlet WKInterfaceLabel * timeRemainingLabel;

-(IBAction) initWithContext:(id) context;
-(IBAction) willActivate;
-(IBAction) didDeactivate;
-(IBAction) refresh;

@end

@interface NotificationController: WKUserNotificationInterfaceController
-(IBAction) init;
-(IBAction) willActivate;
-(IBAction) didDeactivate;

@end

