# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios-extension'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Widget'
  app.info_plist['CFBundleDisplayName'] = 'Forking Pasta'
  app.frameworks << "NotificationCenter"
  app.info_plist['NSExtension'] = {
    'NSExtensionMainStoryboard' => 'MainInterface',
    'NSExtensionPointIdentifier' => 'com.apple.widget-extension'
  }
  app.entitlements['com.apple.security.application-groups'] = ['group.uk.pixlwave.ForkingPasta']

  app.target('../KingPastaKit', :framework)

  app.development do
    app.provisioning_profile = '/Users/Douglas/Documents/RubyMotion/Certificates/Forking_Pasta_Widget_development.mobileprovision'
  end

  app.release do
    app.provisioning_profile = '/Users/Douglas/Documents/RubyMotion/Certificates/Forking_Pasta_Widget.mobileprovision'
  end
end