# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion3.1/lib")
require 'motion/project/template/ios-extension'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Forking Pasta'
  app.frameworks << "NotificationCenter"
  app.info_plist['NSExtension'] = {
    'NSExtensionPrincipalClass' => 'TodayViewController',
    'NSExtensionPointIdentifier' => 'com.apple.widget-extension'
  }
  app.entitlements['com.apple.security.application-groups'] = ['group.uk.pixlwave.ForkingPasta']

  app.target('../KingPastaKit', :framework)
end

task :"build:simulator" => :"schema:build"