# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios-watch-extension'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.info_plist['CFBundleDisplayName'] = 'Forking Pasta'

  app.entitlements['com.apple.security.application-groups'] = ['group.uk.pixlwave.ForkingPasta']

  app.target('../KingPastaKit', :framework)
end

IB::RakeTask.new do |project|
  project.resource_directories = ['watch_app']
end
