# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios-watch-extension'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.entitlements['com.apple.security.application-groups'] = ['group.uk.pixlwave.ForkingPasta']
  app.deployment_target = '8.2'
  app.watch_app_config.deployment_target = '8.2'

  app.target('../KingPastaKit', :framework)

  app.development do
    app.provisioning_profile = '/Users/Douglas/Documents/RubyMotion/Certificates/Forking_Pasta_Watch_Extension_development.mobileprovision'
    app.watch_app_config.provisioning_profile = "/Users/Douglas/Documents/RubyMotion/Certificates/Forking_Pasta_Watch_App_development.mobileprovision"
  end

  app.release do
    app.provisioning_profile = '/Users/Douglas/Documents/RubyMotion/Certificates/Forking_Pasta_Watch_Extension.mobileprovision'
    app.watch_app_config.provisioning_profile = "/Users/Douglas/Documents/RubyMotion/Certificates/Forking_Pasta_Watch_App.mobileprovision"
  end
end

IB::RakeTask.new do |project|
  project.resource_directories = ['watch_app']
end
