// Generated by IB v0.7.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <NotificationCenter/NotificationCenter.h>

@interface TodayViewController: UIViewController

@property IBOutlet UIImageView * clockImageView;
@property IBOutlet UILabel * periodNameLabel;
@property IBOutlet UILabel * timeRemainingLabel;

-(IBAction) viewDidLoad;
-(IBAction) didReceiveMemoryWarning;
-(IBAction) viewDidAppear:(id) animated;
-(IBAction) viewWillDisappear:(id) animated;
-(IBAction) refresh;
-(IBAction) widgetPerformUpdateWithCompletionHandler:(id) completionHandler;
-(IBAction) widgetMarginInsetsForProposedMarginInsets:(id) defaultMarginInsets;

@end

