// Generated by IB v0.7.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation DetailController
@end

@implementation EditCategoryController
@end

@implementation MainController
@end

@implementation OverviewController
@end

@implementation SelectCategoryController
@end

@implementation SetTimeController
@end

@implementation CategoryColorMark
@end

@implementation CategoryColorCell
@end

@implementation CategoryNameCell
@end

@implementation PeriodCategoryCell
@end

@implementation PeriodColorMark
@end

@implementation PeriodCell
@end

@implementation PeriodDayCell
@end

@implementation PeriodNameCell
@end

@implementation SelectCategoryCell
@end

