// Generated by IB v0.7.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
-(IBAction) setupDefaultCategories;

@end

@interface DetailController: UITableViewController

@property IBOutlet UIBarButtonItem * saveButton;
@property IBOutlet UITextField * nameTextField;
@property IBOutlet UIDatePicker * startTimePicker;
@property IBOutlet UISwitch * mondaySwitch;
@property IBOutlet UISwitch * tuesdaySwitch;
@property IBOutlet UISwitch * wednesdaySwitch;
@property IBOutlet UISwitch * thursdaySwitch;
@property IBOutlet UISwitch * fridaySwitch;
@property IBOutlet UISwitch * saturdaySwitch;
@property IBOutlet UISwitch * sundaySwitch;

-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) validate;
-(IBAction) save;
-(IBAction) cancel;
-(IBAction) nameDidChange:(id) sender;
-(IBAction) daysDidChange:(id) sender;
-(IBAction) textFieldShouldReturn:(id) textField;
-(IBAction) numberOfSectionsInTableView:(id) tableView;

@end

@interface MainController: UIViewController

@property IBOutlet UIView * watchView;
@property IBOutlet UIImageView * clockImageView;
@property IBOutlet UILabel * periodNameLabel;
@property IBOutlet UILabel * timeRemainingLabel;

-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) viewDidAppear:(id) animated;
-(IBAction) viewWillDisappear:(id) animated;
-(IBAction) redraw;

@end

@interface OverviewController: UITableViewController

@property IBOutlet UISegmentedControl * dayControl;

-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) viewWillDisappear:(id) animated;
-(IBAction) dismiss;
-(IBAction) dayChanged;

@end

@interface SelectCategoryController: UITableViewController
@end

@interface SetTimeController: UIViewController

@property IBOutlet UIDatePicker * timePicker;

-(IBAction) viewDidLoad;
-(IBAction) done;

@end

@interface CategoryColorMark: UIView
-(IBAction) layoutSubviews;
-(IBAction) color;

@end

@interface CategoryCell: UITableViewCell

@property IBOutlet UILabel * nameLabel;
@property IBOutlet CategoryColorMark * colorMark;

@end

@interface PeriodCell: UITableViewCell

@property IBOutlet UIView * categoryColorMark;
@property IBOutlet UILabel * periodNameLabel;
@property IBOutlet UILabel * timeRangeLabel;

@end

@interface PeriodDayCell: UITableViewCell

@property IBOutlet UILabel * dayLabel;
@property IBOutlet UISwitch * daySwitch;

@end

@interface PeriodNameCell: UITableViewCell

@property IBOutlet UITextField * nameTextField;

@end

@interface SelectCategoryCell: UITableViewCell

@property IBOutlet UILabel * nameLabel;
@property IBOutlet CategoryColorMark * colorView;

@end

