// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation CategoryController
@end

@implementation EditCategoryController
@end

@implementation MainController
@end

@implementation PeriodDetailController
@end

@implementation ScheduleController
@end

@implementation ScheduleDaysController
@end

@implementation ScheduleDetailController
@end

@implementation SelectCategoryController
@end

@implementation SetTimeController
@end

@implementation WakeBedTimeController
@end

@implementation CategoryColorMark
@end

@implementation CategoryColorCell
@end

@implementation CategoryNameCell
@end

@implementation PeriodCategoryCell
@end

@implementation PeriodColorMark
@end

@implementation PeriodCell
@end

@implementation PeriodDayCell
@end

@implementation PeriodNameCell
@end

@implementation SelectCategoryCell
@end

