// Generated by IB v0.7.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation DetailController
@end

@implementation EditController
@end

@implementation MainController
@end

@implementation SelectCategoryController
@end

@implementation SetTimeController
@end

@implementation Category
@end

@implementation Clock
@end

@implementation Day
@end

@implementation Period
@end

@implementation Time
@end

@implementation PeriodDayCell
@end

@implementation PeriodNameCell
@end

